version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: deploy/api.dockerfile
    image: frand-api:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports: 
      - ${ROCKET_PORT}:${ROCKET_PORT}
    networks:
      - frand-api-network

networks:
  frand-api-network:
    driver: bridge