[build]
# Build in release mode
release = false

[watch]
# Watch these directories for changes
watch = ["src", "static", "index.html"]

[serve]
# The address to serve on
address = "127.0.0.1"
# The port to serve on
port = 8080
# Open a browser tab once the server started
open = true
